server:
  port: ${SPRING_PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:login_user}
    password: ${SPRING_DATASOURCE_PASSWORD:login_pw}
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            # ⭐ redirect-uri 수정
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-name: Kakao
            # ⭐ client-authentication-method 추가
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: "${GMAIL_USERNAME}"
    password: "${GMAIL_PASSWORD}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}     # Docker 네트워크에서 rabbitmq 컨테이너명으로
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

jwt:
  issuer: daeun1q2w3e@gmail.com
  secret_key: ${JWT_SECRET}
  access-token-expiration: 900000
  refresh-token-expiration: 1209600000

rabbitmq:
  exchange:
    email: email.exchange
  queue:
    email: email.queue
  routing-key:
    email: email.routing.key

# ⭐ 디버깅용 로그 설정 추가
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    hello.wink_bootcamp.domain.oauth: DEBUG
    org.springframework.web: DEBUG