server:
  port: ${SPRING_PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:login_user}
    password: ${SPRING_DATASOURCE_PASSWORD:login_pw}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: "${GMAIL_USERNAME}"
    password: "${GMAIL_PASSWORD}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}     # Docker 네트워크에서 rabbitmq 컨테이너명으로
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

jwt:
  issuer: daeun1q2w3e@gmail.com
  secret_key: ${JWT_SECRET}

rabbitmq:
  exchange:
    email: email.exchange
  queue:
    email: email.queue
  routing-key:
    email: email.routing.key