server:
  port: ${SPRING_PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:login_user}
    password: ${SPRING_DATASOURCE_PASSWORD:login_pw}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${SPRING_REDIS_HOST:localhost}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

jwt:
  issuer: daeun1q2w3e@gmail.com
  secret_key: ${JWT_SECRET}