name: CI/CD - GHCR → EC2 배포

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v3

      - name: 이미지 태그 설정 (날짜+커밋해시)
        id: vars
        run: echo "IMAGE_TAG=$(date +%Y-%m-%d)-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: GHCR 로그인
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Docker 이미지 빌드 및 태그
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/backend:latest .
          docker tag ghcr.io/${{ secrets.GHCR_USERNAME }}/backend:latest ghcr.io/${{ secrets.GHCR_USERNAME }}/backend:${{ env.IMAGE_TAG }}

      - name: GHCR로 이미지 푸시
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/backend:latest
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/backend:${{ env.IMAGE_TAG }}

      - name: EC2에 SSH로 접속해 Docker 실행
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/app     # docker-compose.yml 이 있는 경로
            docker-compose pull
            docker-compose up -d